version: "4"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=YVznoqDqwatTsnfHHQEbRpgUmljdQudO
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:YVznoqDqwatTsnfHHQEbRpgUmljdQudO@mongodb.railway.internal:27017
      - APP_ORIGIN=http://growthbook-production.up.railway.app:3000
      - API_HOST=http://growthbook-production.up.railway.app:3100
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
